name: build on linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
  
    - name: Install system packages required for Flutter desktop
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          libgtk-3-dev liblzma-dev libgl1-mesa-dev libglu1-mesa-dev \
          libasound2-dev libpulse-dev build-essential clang cmake ninja-build pkg-config

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Show Flutter version and doctor
      run: |
        flutter --version
        flutter doctor -v

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
        pip install .
        pip install "flet[all]"

    - name: Lint with ruff
      run: ruff check .

    - name: Build with flet (verbose)
      run: flet build linux --verbose

    - name: Package the build/linux directory
      run: tar -czvf build_linux.tar.gz -C build/linux .

    - name: Upload the build products
      uses: actions/upload-artifact@v4
      with:
        name: build_linux
        path: build_linux.tar.gz
