name: build on linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Debug runner path
      run: |
        echo "PATH=$PATH"
        uname -a
    - name: Install Flutter (manual)
      run: |
        set -e
        echo "Installing Flutter stable into $HOME/flutter"
        rm -rf $HOME/flutter
        git clone --depth 1 https://github.com/flutter/flutter.git -b stable $HOME/flutter
        echo "$HOME/flutter/bin" >> $GITHUB_PATH
        export PATH="$HOME/flutter/bin:$PATH"
        flutter --version
        flutter doctor -v
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        flutter --version
        flutter doctor -v
        python -m pip install --upgrade pip
        pip install ruff
        pip install .
        pip install flet[all]
        sudo apt install libgtk-3-dev
    - name: Lint with ruff
      run: |
        ruff check .
    - name: Build with flet
      run: |
        flet build linux
    - name: Package the build/linux directory
      run: |
        tar -czvf build_linux.tar.gz -C build/linux .
    - name: Upload the build products
      uses: actions/upload-artifact@v4
      with:
        name: build_linux
        path: build_linux.tar.gz
