name: Build Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-windows:
    name: Build Windows (flet build windows)
    runs-on: windows-latest
    env:
      PYTHONUTF8: 1
      PYTHONIOENCODING: utf-8

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install flet and deps
        shell: powershell
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install flet

      - name: Verify Visual Studio 2022 with Desktop C++ workload
        shell: powershell
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-not (Test-Path $vswhere)) { Write-Error "vswhere not found on runner"; exit 1 }
          $info = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
          if (-not $info) { Write-Error "Visual Studio with Desktop development with C++ workload not found"; exit 1 }
          Write-Host "Found Visual Studio at: $info"

      - name: Build Windows with flet
        shell: powershell
        run: |
          # ensure console uses UTF-8 so rich can print special characters
          chcp 65001 | Out-Null
          [Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8
          $OutputEncoding = New-Object -typename System.Text.UTF8Encoding
          flet build windows

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flet-windows-build
          path: |
            ./build
            ./dist
            ./output